"""add_page_view_to_eventtype_enum

Revision ID: 0559324f120b
Revises: 7278633aa5e9
Create Date: 2026-01-11 22:27:43.564293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0559324f120b'
down_revision: Union[str, Sequence[str], None] = '7278633aa5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'PAGE_VIEW' BEFORE 'ERROR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
