"""add_provider_column_to_credentials

Revision ID: 1381db9ee598
Revises: 63cf67facefa
Create Date: 2025-12-23 09:34:33.035512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1381db9ee598'
down_revision: Union[str, Sequence[str], None] = '63cf67facefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('provider', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_credentials_provider'), 'credentials', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_provider'), table_name='credentials')
    op.drop_column('credentials', 'provider')
    # ### end Alembic commands ###
