"""Add is_default field to organizations table

Revision ID: 144563994efd
Revises: 890b361d4089
Create Date: 2025-12-04 20:31:21.650620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144563994efd'
down_revision: Union[str, Sequence[str], None] = '890b361d4089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable
    op.add_column('organizations', sa.Column('is_default', sa.Boolean(), nullable=True))

    # Set default value for existing organizations (False for all existing ones)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE organizations SET is_default = FALSE WHERE is_default IS NULL"))

    # Now make the column NOT NULL
    op.alter_column('organizations', 'is_default', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_default')
    # ### end Alembic commands ###
