"""add_workspace_id_to_notifications

Revision ID: 1486a632dca2
Revises: 7f59f7b0d2af
Create Date: 2026-04-26 17:18:00.674549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1486a632dca2'
down_revision: Union[str, Sequence[str], None] = '7f59f7b0d2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index('idx_notif_user_workspace', 'notifications', ['user_id', 'workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index('idx_notif_user_workspace', table_name='notifications')
    op.drop_column('notifications', 'workspace_id')
    # ### end Alembic commands ###
