"""add_context_field_to_knowledge_base

Revision ID: 185d2379d2c0
Revises: 890e849f1044
Create Date: 2025-11-16 05:22:15.680452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185d2379d2c0'
down_revision: Union[str, Sequence[str], None] = '890e849f1044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('context', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_knowledge_bases_context'), 'knowledge_bases', ['context'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bases_context'), table_name='knowledge_bases')
    op.drop_column('knowledge_bases', 'context')
    # ### end Alembic commands ###
