"""add widget_events and credentials tables

Revision ID: 2ead938281e6
Revises: 542f44068e22
Create Date: 2025-12-22 13:20:30.185836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ead938281e6'
down_revision: Union[str, Sequence[str], None] = '542f44068e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('bot_type', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('WIDGET_LOADED', 'WIDGET_OPENED', 'WIDGET_CLOSED', 'MESSAGE_SENT', 'MESSAGE_RECEIVED', 'LEAD_COLLECTED', 'LEAD_SKIPPED', 'FEEDBACK_GIVEN', 'ERROR', name='eventtype'), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_events_bot_id'), 'widget_events', ['bot_id'], unique=False)
    op.create_index('ix_widget_events_bot_time', 'widget_events', ['bot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_widget_events_created_at'), 'widget_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_widget_events_event_type'), 'widget_events', ['event_type'], unique=False)
    op.create_index('ix_widget_events_session', 'widget_events', ['bot_id', 'session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_widget_events_session_id'), 'widget_events', ['session_id'], unique=False)
    op.create_index('ix_widget_events_type_time', 'widget_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_widget_events_workspace_id'), 'widget_events', ['workspace_id'], unique=False)
    op.create_index('ix_widget_events_workspace_time', 'widget_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_type', sa.Enum('API_KEY', 'OAUTH2', 'BASIC_AUTH', 'DATABASE', 'SMTP', 'AWS', 'CUSTOM', name='credentialtype'), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_credential_type'), 'credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_is_active'), 'credentials', ['is_active'], unique=False)
    op.create_index('ix_credentials_workspace_active', 'credentials', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_credentials_workspace_id'), 'credentials', ['workspace_id'], unique=False)
    op.create_index('ix_credentials_workspace_type', 'credentials', ['workspace_id', 'credential_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credentials_workspace_type', table_name='credentials')
    op.drop_index(op.f('ix_credentials_workspace_id'), table_name='credentials')
    op.drop_index('ix_credentials_workspace_active', table_name='credentials')
    op.drop_index(op.f('ix_credentials_is_active'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_type'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_widget_events_workspace_time', table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_workspace_id'), table_name='widget_events')
    op.drop_index('ix_widget_events_type_time', table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_session_id'), table_name='widget_events')
    op.drop_index('ix_widget_events_session', table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_event_type'), table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_created_at'), table_name='widget_events')
    op.drop_index('ix_widget_events_bot_time', table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_bot_id'), table_name='widget_events')
    op.drop_table('widget_events')
    # ### end Alembic commands ###
