"""add_missing_kb_fields

Revision ID: 3b2a942d5b19
Revises: e5c1c1c3f41b
Create Date: 2025-11-19 02:38:16.105976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3b2a942d5b19'
down_revision: Union[str, Sequence[str], None] = 'e5c1c1c3f41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension is installed (safe if already exists)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=True),
    sa.Column('chunks_used', sa.Integer(), nullable=True),
    sa.Column('chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_ms', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbanalytics_context_created', 'kb_analytics_events', ['context', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_kb_created', 'kb_analytics_events', ['kb_id', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_session', 'kb_analytics_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_type_created', 'kb_analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_context'), 'kb_analytics_events', ['context'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_created_at'), 'kb_analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_event_type'), 'kb_analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_kb_id'), 'kb_analytics_events', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_session_id'), 'kb_analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_user_id'), 'kb_analytics_events', ['user_id'], unique=False)
    op.create_table('kb_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbaudit_action_created', 'kb_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_kbaudit_created', 'kb_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_kbaudit_kb_created', 'kb_audit_logs', ['kb_id', 'created_at'], unique=False)
    op.create_index('idx_kbaudit_user_created', 'kb_audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_action'), 'kb_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_created_at'), 'kb_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_kb_id'), 'kb_audit_logs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_target_type'), 'kb_audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_user_id'), 'kb_audit_logs', ['user_id'], unique=False)
    op.create_table('kb_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kb_id', name='uq_user_kb')
    )
    op.create_index('idx_kbmember_kb', 'kb_members', ['kb_id'], unique=False)
    op.create_index('idx_kbmember_role', 'kb_members', ['role'], unique=False)
    op.create_index('idx_kbmember_user', 'kb_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_kb_members_kb_id'), 'kb_members', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_members_role'), 'kb_members', ['role'], unique=False)
    op.create_index(op.f('ix_kb_members_user_id'), 'kb_members', ['user_id'], unique=False)
    op.create_table('kb_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbnotif_kb_event', 'kb_notifications', ['kb_id', 'event'], unique=False)
    op.create_index('idx_kbnotif_status_scheduled', 'kb_notifications', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_kbnotif_user_created', 'kb_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_notifications_channel'), 'kb_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_kb_notifications_created_at'), 'kb_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_notifications_event'), 'kb_notifications', ['event'], unique=False)
    op.create_index(op.f('ix_kb_notifications_kb_id'), 'kb_notifications', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_notifications_status'), 'kb_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_kb_notifications_user_id'), 'kb_notifications', ['user_id'], unique=False)
    op.add_column('chunks', sa.Column('kb_id', sa.UUID(), nullable=False))
    op.alter_column('chunks', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('chunks', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('chunks', 'embedding_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('idx_chunk_content_hash'), table_name='chunks')
    op.drop_index(op.f('idx_chunk_doc_position'), table_name='chunks')
    op.drop_index(op.f('idx_chunk_embedding_id'), table_name='chunks')
    op.drop_index(op.f('idx_chunk_enabled_quality'), table_name='chunks')
    op.drop_index(op.f('idx_chunk_keywords'), table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_chunk_last_retrieved'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_embedding_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_kb_id'), 'chunks', ['kb_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunks', 'related_chunks')
    op.add_column('documents', sa.Column('kb_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('documents', 'content_preview',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('documents', 'processing_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('documents', 'auto_disabled_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_doc_created_by'), table_name='documents')
    op.drop_index(op.f('idx_doc_kb_enabled_archived'), table_name='documents')
    op.drop_index(op.f('idx_doc_kb_status'), table_name='documents')
    op.drop_index(op.f('idx_doc_last_accessed'), table_name='documents')
    op.drop_index(op.f('idx_doc_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_archived'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_enabled'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('documents_knowledge_base_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'knowledge_base_id')
    op.add_column('knowledge_bases', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('knowledge_bases', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('knowledge_bases', sa.Column('context', sa.String(length=50), nullable=False))
    op.add_column('knowledge_bases', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_kb_created_by'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_kb_last_indexed'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_kb_workspace_active'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_is_deleted'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_context'), 'knowledge_bases', ['context'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_status'), 'knowledge_bases', ['status'], unique=False)
    op.drop_column('knowledge_bases', 'is_deleted')
    op.drop_column('knowledge_bases', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Note: We don't drop the vector extension as it may be used by other schemas
    # If needed, manually run: DROP EXTENSION IF EXISTS vector CASCADE;

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('knowledge_bases', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_knowledge_bases_status'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_context'), table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_is_deleted'), 'knowledge_bases', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_kb_workspace_active'), 'knowledge_bases', ['workspace_id', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_kb_last_indexed'), 'knowledge_bases', ['last_indexed_at'], unique=False)
    op.create_index(op.f('idx_kb_created_by'), 'knowledge_bases', ['created_by'], unique=False)
    op.drop_column('knowledge_bases', 'stats')
    op.drop_column('knowledge_bases', 'error_message')
    op.drop_column('knowledge_bases', 'processed_at')
    op.drop_column('knowledge_bases', 'context')
    op.drop_column('knowledge_bases', 'config')
    op.drop_column('knowledge_bases', 'status')
    op.add_column('documents', sa.Column('knowledge_base_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_knowledge_base_id_fkey'), 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_documents_is_enabled'), 'documents', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_documents_is_archived'), 'documents', ['is_archived'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=True)
    op.create_index(op.f('idx_doc_source_type'), 'documents', ['source_type'], unique=False)
    op.create_index(op.f('idx_doc_last_accessed'), 'documents', ['last_accessed_at'], unique=False)
    op.create_index(op.f('idx_doc_kb_status'), 'documents', ['knowledge_base_id', 'status'], unique=False)
    op.create_index(op.f('idx_doc_kb_enabled_archived'), 'documents', ['knowledge_base_id', 'is_enabled', 'is_archived'], unique=False)
    op.create_index(op.f('idx_doc_created_by'), 'documents', ['created_by'], unique=False)
    op.alter_column('documents', 'auto_disabled_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('documents', 'processing_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('documents', 'content_preview',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('documents', 'workspace_id')
    op.drop_column('documents', 'kb_id')
    op.add_column('chunks', sa.Column('related_chunks', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_kb_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=True)
    op.create_index(op.f('ix_chunks_embedding_id'), 'chunks', ['embedding_id'], unique=False)
    op.create_index(op.f('idx_chunk_last_retrieved'), 'chunks', ['last_retrieved_at'], unique=False)
    op.create_index(op.f('idx_chunk_keywords'), 'chunks', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chunk_enabled_quality'), 'chunks', ['is_enabled', 'quality_score'], unique=False)
    op.create_index(op.f('idx_chunk_embedding_id'), 'chunks', ['embedding_id'], unique=False)
    op.create_index(op.f('idx_chunk_doc_position'), 'chunks', ['document_id', 'position'], unique=False)
    op.create_index(op.f('idx_chunk_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.alter_column('chunks', 'embedding_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('chunks', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('chunks', 'kb_id')
    op.drop_index(op.f('ix_kb_notifications_user_id'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_status'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_kb_id'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_event'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_created_at'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_channel'), table_name='kb_notifications')
    op.drop_index('idx_kbnotif_user_created', table_name='kb_notifications')
    op.drop_index('idx_kbnotif_status_scheduled', table_name='kb_notifications')
    op.drop_index('idx_kbnotif_kb_event', table_name='kb_notifications')
    op.drop_table('kb_notifications')
    op.drop_index(op.f('ix_kb_members_user_id'), table_name='kb_members')
    op.drop_index(op.f('ix_kb_members_role'), table_name='kb_members')
    op.drop_index(op.f('ix_kb_members_kb_id'), table_name='kb_members')
    op.drop_index('idx_kbmember_user', table_name='kb_members')
    op.drop_index('idx_kbmember_role', table_name='kb_members')
    op.drop_index('idx_kbmember_kb', table_name='kb_members')
    op.drop_table('kb_members')
    op.drop_index(op.f('ix_kb_audit_logs_user_id'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_target_type'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_kb_id'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_created_at'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_action'), table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_user_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_kb_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_action_created', table_name='kb_audit_logs')
    op.drop_table('kb_audit_logs')
    op.drop_index(op.f('ix_kb_analytics_events_user_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_session_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_kb_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_event_type'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_created_at'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_context'), table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_type_created', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_session', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_kb_created', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_context_created', table_name='kb_analytics_events')
    op.drop_table('kb_analytics_events')
    # ### end Alembic commands ###
