"""add lead lat/lng columns

Revision ID: 41b40d486422
Revises: 96404abb875a
Create Date: 2026-05-02 15:21:08.448624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b40d486422'
down_revision: Union[str, Sequence[str], None] = '96404abb875a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    # ### end Alembic commands ###
