"""add_referrals_and_user_referral_code

Revision ID: 5000eb773e1a
Revises: c5ecd5ee2d8e
Create Date: 2026-04-27 19:04:53.443508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5000eb773e1a'
down_revision: Union[str, Sequence[str], None] = 'c5ecd5ee2d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referrals_referrer_status', 'referrals', ['referrer_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_referrals_email'), 'referrals', ['email'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=True)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.add_column('users', sa.Column('referral_code', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referral_code')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_email'), table_name='referrals')
    op.drop_index('idx_referrals_referrer_status', table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
