"""add chatbot api_key chat_session chat_message tables

Revision ID: 542f44068e22
Revises: e61c856e62fc
Create Date: 2025-12-19 18:30:44.382102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '542f44068e22'
down_revision: Union[str, Sequence[str], None] = 'e61c856e62fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_type', sa.Enum('CHATBOT', 'CHATFLOW', name='bottype'), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'CLOSED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_bot_id'), 'chat_sessions', ['bot_id'], unique=False)
    op.create_index('ix_chat_sessions_bot_lookup', 'chat_sessions', ['bot_type', 'bot_id', 'status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_bot_type'), 'chat_sessions', ['bot_type'], unique=False)
    op.create_index('ix_chat_sessions_cleanup', 'chat_sessions', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_expires_at'), 'chat_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('ix_chat_sessions_workspace', 'chat_sessions', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_workspace_id'), 'chat_sessions', ['workspace_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'MARKDOWN', 'HTML', 'IMAGE', 'FILE', name='contenttype'), nullable=False),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_feedback', 'chat_messages', ['feedback'], unique=False, postgresql_where=sa.text('feedback IS NOT NULL'))
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index('ix_chat_messages_role_created', 'chat_messages', ['role', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_workspace_created', 'chat_messages', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_workspace_id'), 'chat_messages', ['workspace_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Enum('WORKSPACE', 'CHATBOT', 'CHATFLOW', 'KNOWLEDGE_BASE', 'PUBLIC', name='keyscopetype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rate_limit_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_entity', 'api_keys', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_api_keys_entity_id'), 'api_keys', ['entity_id'], unique=False)
    op.create_index('ix_api_keys_expires', 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_index('ix_api_keys_workspace_scope', 'api_keys', ['workspace_id', 'scope_type', 'is_active'], unique=False)
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='chatbotstatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kb_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('branding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployment_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavior_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lead_capture_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analytics_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cached_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbots_created_at', 'chatbots', ['created_at'], unique=False)
    op.create_index('ix_chatbots_slug', 'chatbots', ['workspace_id', 'slug'], unique=True)
    op.create_index(op.f('ix_chatbots_status'), 'chatbots', ['status'], unique=False)
    op.create_index(op.f('ix_chatbots_workspace_id'), 'chatbots', ['workspace_id'], unique=False)
    op.create_index('ix_chatbots_workspace_status', 'chatbots', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatbots_workspace_status', table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_workspace_id'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_status'), table_name='chatbots')
    op.drop_index('ix_chatbots_slug', table_name='chatbots')
    op.drop_index('ix_chatbots_created_at', table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index('ix_api_keys_workspace_scope', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index('ix_api_keys_expires', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_entity_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_entity', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_chat_messages_workspace_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_workspace_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_index('ix_chat_messages_role_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_feedback', table_name='chat_messages', postgresql_where=sa.text('feedback IS NOT NULL'))
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_workspace_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_workspace', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_updated_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_expires_at'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_cleanup', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_bot_type'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_bot_lookup', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_bot_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
