"""add_lead_consent_fields

Revision ID: 5a64a22fc440
Revises: 1381db9ee598
Create Date: 2025-12-23 11:06:05.843862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a64a22fc440'
down_revision: Union[str, Sequence[str], None] = '1381db9ee598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('bot_type', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('consent_given', sa.String(length=1), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('consent_method', sa.String(length=50), nullable=True),
    sa.Column('data_processing_agreed', sa.String(length=1), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'UNQUALIFIED', name='leadstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_captured_at', 'leads', ['captured_at'], unique=False)
    op.create_index('idx_leads_workspace_bot', 'leads', ['workspace_id', 'bot_id'], unique=False)
    op.create_index(op.f('ix_leads_bot_id'), 'leads', ['bot_id'], unique=False)
    op.create_index(op.f('ix_leads_channel'), 'leads', ['channel'], unique=False)
    op.create_index(op.f('ix_leads_country'), 'leads', ['country'], unique=False)
    op.create_index(op.f('ix_leads_country_code'), 'leads', ['country_code'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=True)
    op.create_index(op.f('ix_leads_session_id'), 'leads', ['session_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_session_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_country_code'), table_name='leads')
    op.drop_index(op.f('ix_leads_country'), table_name='leads')
    op.drop_index(op.f('ix_leads_channel'), table_name='leads')
    op.drop_index(op.f('ix_leads_bot_id'), table_name='leads')
    op.drop_index('idx_leads_workspace_bot', table_name='leads')
    op.drop_index('idx_leads_captured_at', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
