"""add_chatflows_table

Revision ID: 61fae9d160d7
Revises: 5a64a22fc440
Create Date: 2025-12-23 23:06:18.113994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61fae9d160d7'
down_revision: Union[str, Sequence[str], None] = '5a64a22fc440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatflows_workspace_active', 'chatflows', ['workspace_id', 'is_active'], unique=False)
    op.create_index('ix_chatflows_workspace_deleted', 'chatflows', ['workspace_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_chatflows_workspace_id'), 'chatflows', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatflows_workspace_id'), table_name='chatflows')
    op.drop_index('ix_chatflows_workspace_deleted', table_name='chatflows')
    op.drop_index('ix_chatflows_workspace_active', table_name='chatflows')
    op.drop_table('chatflows')
    # ### end Alembic commands ###
