"""add_variables_config_to_chatbots

Revision ID: 63cf67facefa
Revises: 7a53751fb370
Create Date: 2025-12-23 08:52:41.833953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63cf67facefa'
down_revision: Union[str, Sequence[str], None] = '7a53751fb370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('variables_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'variables_config')
    # ### end Alembic commands ###
