"""add_slug_to_workspaces

Revision ID: 7278633aa5e9
Revises: e2b400fd17e2
Create Date: 2026-01-11 04:54:16.694138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7278633aa5e9'
down_revision: Union[str, Sequence[str], None] = 'e2b400fd17e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index('idx_workspace_slug', 'workspaces', ['slug'], unique=False)
    op.create_unique_constraint(None, 'workspaces', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_index('idx_workspace_slug', table_name='workspaces')
    op.drop_column('workspaces', 'slug')
    # ### end Alembic commands ###
