"""add_chatbot_archive_audit_fields

Revision ID: 7a53751fb370
Revises: 2ead938281e6
Create Date: 2025-12-22 16:40:09.931407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a53751fb370'
down_revision: Union[str, Sequence[str], None] = '2ead938281e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('chatbots', sa.Column('archived_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chatbots', 'users', ['archived_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbots', type_='foreignkey')
    op.drop_column('chatbots', 'archived_by')
    op.drop_column('chatbots', 'archived_at')
    # ### end Alembic commands ###
