"""add_slack_workspace_deployments

Revision ID: 7f59f7b0d2af
Revises: 777fd4fd2c51
Create Date: 2026-04-01 07:00:06.407180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f59f7b0d2af'
down_revision: Union[str, Sequence[str], None] = '777fd4fd2c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspace_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=True),
    sa.Column('team_domain', sa.String(length=200), nullable=True),
    sa.Column('team_icon', sa.String(length=500), nullable=True),
    sa.Column('bot_token_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('bot_user_id', sa.String(length=100), nullable=True),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('allowed_channel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slack_workspace_active', 'slack_workspace_deployments', ['team_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_slack_workspace_deployments_chatbot_id'), 'slack_workspace_deployments', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_slack_workspace_deployments_team_id'), 'slack_workspace_deployments', ['team_id'], unique=True)
    op.create_index(op.f('ix_slack_workspace_deployments_workspace_id'), 'slack_workspace_deployments', ['workspace_id'], unique=False)
    op.create_index('ix_slack_workspace_workspace_chatbot', 'slack_workspace_deployments', ['workspace_id', 'chatbot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slack_workspace_workspace_chatbot', table_name='slack_workspace_deployments')
    op.drop_index(op.f('ix_slack_workspace_deployments_workspace_id'), table_name='slack_workspace_deployments')
    op.drop_index(op.f('ix_slack_workspace_deployments_team_id'), table_name='slack_workspace_deployments')
    op.drop_index(op.f('ix_slack_workspace_deployments_chatbot_id'), table_name='slack_workspace_deployments')
    op.drop_index('ix_slack_workspace_active', table_name='slack_workspace_deployments')
    op.drop_table('slack_workspace_deployments')
    # ### end Alembic commands ###
