"""Add content_full field to documents table

Revision ID: 890b361d4089
Revises: 3b2a942d5b19
Create Date: 2025-11-20 17:45:58.710468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890b361d4089'
down_revision: Union[str, Sequence[str], None] = '3b2a942d5b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_full', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_full')
    # ### end Alembic commands ###
