"""add_invitations_table

Revision ID: a680b994bafd
Revises: af049a07de1b
Create Date: 2025-10-30 17:43:16.442562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a680b994bafd'
down_revision: Union[str, Sequence[str], None] = 'af049a07de1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invited_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("resource_type IN ('organization', 'workspace')", name='check_resource_type'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'expired', 'cancelled')", name='check_status'),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invitation_email', 'invitations', ['email'], unique=False)
    op.create_index('idx_invitation_resource', 'invitations', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_invitation_status', 'invitations', ['status'], unique=False)
    op.create_index('idx_invitation_token', 'invitations', ['token'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_resource_id'), 'invitations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_invitations_resource_type'), 'invitations', ['resource_type'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_resource_type'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_resource_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index('idx_invitation_token', table_name='invitations')
    op.drop_index('idx_invitation_status', table_name='invitations')
    op.drop_index('idx_invitation_resource', table_name='invitations')
    op.drop_index('idx_invitation_email', table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
