"""add_discord_guild_deployments

Revision ID: b1a30eec0e64
Revises: c88464ddecb0
Create Date: 2026-01-25 16:14:36.061254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a30eec0e64'
down_revision: Union[str, Sequence[str], None] = 'c88464ddecb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_guild_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(length=100), nullable=False),
    sa.Column('guild_name', sa.String(length=200), nullable=True),
    sa.Column('guild_icon', sa.String(length=500), nullable=True),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('allowed_channel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('guild_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discord_guild_active', 'discord_guild_deployments', ['guild_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_discord_guild_deployments_chatbot_id'), 'discord_guild_deployments', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_discord_guild_deployments_guild_id'), 'discord_guild_deployments', ['guild_id'], unique=True)
    op.create_index(op.f('ix_discord_guild_deployments_workspace_id'), 'discord_guild_deployments', ['workspace_id'], unique=False)
    op.create_index('ix_discord_guild_workspace_chatbot', 'discord_guild_deployments', ['workspace_id', 'chatbot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discord_guild_workspace_chatbot', table_name='discord_guild_deployments')
    op.drop_index(op.f('ix_discord_guild_deployments_workspace_id'), table_name='discord_guild_deployments')
    op.drop_index(op.f('ix_discord_guild_deployments_guild_id'), table_name='discord_guild_deployments')
    op.drop_index(op.f('ix_discord_guild_deployments_chatbot_id'), table_name='discord_guild_deployments')
    op.drop_index('ix_discord_guild_active', table_name='discord_guild_deployments')
    op.drop_table('discord_guild_deployments')
    # ### end Alembic commands ###
