"""add is_public to chatflows

Revision ID: b22d1c780092
Revises: 418102d6f547
Create Date: 2026-02-01 14:06:53.689763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22d1c780092'
down_revision: Union[str, Sequence[str], None] = '418102d6f547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatflows', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatflows', 'is_public')
    # ### end Alembic commands ###
