"""add_slug_history_table

Revision ID: b686a597e5e8
Revises: b1a30eec0e64
Create Date: 2026-01-25 16:55:09.542051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b686a597e5e8'
down_revision: Union[str, Sequence[str], None] = 'b1a30eec0e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slug_history',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_slug', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('new_slug', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slug_history_cooldown', 'slug_history', ['entity_type', 'old_slug', 'expires_at'], unique=False)
    op.create_index('ix_slug_history_entity', 'slug_history', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_slug_history_id'), 'slug_history', ['id'], unique=True)
    op.create_index('ix_slug_history_lookup', 'slug_history', ['entity_type', 'old_slug', 'workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slug_history_lookup', table_name='slug_history')
    op.drop_index(op.f('ix_slug_history_id'), table_name='slug_history')
    op.drop_index('ix_slug_history_entity', table_name='slug_history')
    op.drop_index('ix_slug_history_cooldown', table_name='slug_history')
    op.drop_table('slug_history')
    # ### end Alembic commands ###
