"""add_chatflow_templates

Revision ID: c5ecd5ee2d8e
Revises: 1486a632dca2
Create Date: 2026-04-27 18:53:29.151799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ecd5ee2d8e'
down_revision: Union[str, Sequence[str], None] = '1486a632dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatflow_templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatflow_templates_category'), 'chatflow_templates', ['category'], unique=False)
    op.create_index(op.f('ix_chatflow_templates_created_by'), 'chatflow_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_chatflow_templates_id'), 'chatflow_templates', ['id'], unique=True)
    op.create_index(op.f('ix_chatflow_templates_slug'), 'chatflow_templates', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatflow_templates_slug'), table_name='chatflow_templates')
    op.drop_index(op.f('ix_chatflow_templates_id'), table_name='chatflow_templates')
    op.drop_index(op.f('ix_chatflow_templates_created_by'), table_name='chatflow_templates')
    op.drop_index(op.f('ix_chatflow_templates_category'), table_name='chatflow_templates')
    op.drop_table('chatflow_templates')
    # ### end Alembic commands ###
