"""discord_guild_deployment_entity_type

Revision ID: d876f78053d0
Revises: d4e5783064df
Create Date: 2026-05-01 11:47:52.976385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd876f78053d0'
down_revision: Union[str, Sequence[str], None] = 'd4e5783064df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_guild_deployments', sa.Column('entity_type', sa.String(length=20), server_default='chatbot', nullable=False))
    op.drop_constraint(op.f('discord_guild_deployments_chatbot_id_fkey'), 'discord_guild_deployments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('discord_guild_deployments_chatbot_id_fkey'), 'discord_guild_deployments', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('discord_guild_deployments', 'entity_type')
    # ### end Alembic commands ###
