"""add_has_beta_access_to_users

Revision ID: e2b400fd17e2
Revises: 71188321296b
Create Date: 2025-12-25 05:36:38.260905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b400fd17e2'
down_revision: Union[str, Sequence[str], None] = '71188321296b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_beta_access', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_beta_access')
    # ### end Alembic commands ###
