"""Add KB RBAC, audit logs, notifications, and analytics tables

Revision ID: e5c1c1c3f41b
Revises: 185d2379d2c0
Create Date: 2025-11-16 07:27:10.305496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c1c1c3f41b'
down_revision: Union[str, Sequence[str], None] = '185d2379d2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=True),
    sa.Column('chunks_used', sa.Integer(), nullable=True),
    sa.Column('chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_ms', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbanalytics_context_created', 'kb_analytics_events', ['context', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_kb_created', 'kb_analytics_events', ['kb_id', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_session', 'kb_analytics_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_kbanalytics_type_created', 'kb_analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_context'), 'kb_analytics_events', ['context'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_created_at'), 'kb_analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_event_type'), 'kb_analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_kb_id'), 'kb_analytics_events', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_session_id'), 'kb_analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_kb_analytics_events_user_id'), 'kb_analytics_events', ['user_id'], unique=False)
    op.create_table('kb_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbaudit_action_created', 'kb_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_kbaudit_created', 'kb_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_kbaudit_kb_created', 'kb_audit_logs', ['kb_id', 'created_at'], unique=False)
    op.create_index('idx_kbaudit_user_created', 'kb_audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_action'), 'kb_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_created_at'), 'kb_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_kb_id'), 'kb_audit_logs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_target_type'), 'kb_audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_kb_audit_logs_user_id'), 'kb_audit_logs', ['user_id'], unique=False)
    op.create_table('kb_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kb_id', name='uq_user_kb')
    )
    op.create_index('idx_kbmember_kb', 'kb_members', ['kb_id'], unique=False)
    op.create_index('idx_kbmember_role', 'kb_members', ['role'], unique=False)
    op.create_index('idx_kbmember_user', 'kb_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_kb_members_kb_id'), 'kb_members', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_members_role'), 'kb_members', ['role'], unique=False)
    op.create_index(op.f('ix_kb_members_user_id'), 'kb_members', ['user_id'], unique=False)
    op.create_table('kb_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbnotif_kb_event', 'kb_notifications', ['kb_id', 'event'], unique=False)
    op.create_index('idx_kbnotif_status_scheduled', 'kb_notifications', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_kbnotif_user_created', 'kb_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kb_notifications_channel'), 'kb_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_kb_notifications_created_at'), 'kb_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_notifications_event'), 'kb_notifications', ['event'], unique=False)
    op.create_index(op.f('ix_kb_notifications_kb_id'), 'kb_notifications', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_notifications_status'), 'kb_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_kb_notifications_user_id'), 'kb_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_notifications_user_id'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_status'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_kb_id'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_event'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_created_at'), table_name='kb_notifications')
    op.drop_index(op.f('ix_kb_notifications_channel'), table_name='kb_notifications')
    op.drop_index('idx_kbnotif_user_created', table_name='kb_notifications')
    op.drop_index('idx_kbnotif_status_scheduled', table_name='kb_notifications')
    op.drop_index('idx_kbnotif_kb_event', table_name='kb_notifications')
    op.drop_table('kb_notifications')
    op.drop_index(op.f('ix_kb_members_user_id'), table_name='kb_members')
    op.drop_index(op.f('ix_kb_members_role'), table_name='kb_members')
    op.drop_index(op.f('ix_kb_members_kb_id'), table_name='kb_members')
    op.drop_index('idx_kbmember_user', table_name='kb_members')
    op.drop_index('idx_kbmember_role', table_name='kb_members')
    op.drop_index('idx_kbmember_kb', table_name='kb_members')
    op.drop_table('kb_members')
    op.drop_index(op.f('ix_kb_audit_logs_user_id'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_target_type'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_kb_id'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_created_at'), table_name='kb_audit_logs')
    op.drop_index(op.f('ix_kb_audit_logs_action'), table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_user_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_kb_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_created', table_name='kb_audit_logs')
    op.drop_index('idx_kbaudit_action_created', table_name='kb_audit_logs')
    op.drop_table('kb_audit_logs')
    op.drop_index(op.f('ix_kb_analytics_events_user_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_session_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_kb_id'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_event_type'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_created_at'), table_name='kb_analytics_events')
    op.drop_index(op.f('ix_kb_analytics_events_context'), table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_type_created', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_session', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_kb_created', table_name='kb_analytics_events')
    op.drop_index('idx_kbanalytics_context_created', table_name='kb_analytics_events')
    op.drop_table('kb_analytics_events')
    # ### end Alembic commands ###
