"""Add missing fields after migration cleanup

Revision ID: e61c856e62fc
Revises: e5c1c1c3f41b
Create Date: 2025-12-17 14:24:56.165283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61c856e62fc'
down_revision: Union[str, Sequence[str], None] = 'e5c1c1c3f41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add missing fields that were lost when cleaning up conflicting migrations

    # Add is_default field to organizations table (from deleted migration 144563994efd)
    op.add_column('organizations', sa.Column('is_default', sa.Boolean(), nullable=True))

    # Set default value for existing organizations (False for all existing ones)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE organizations SET is_default = FALSE WHERE is_default IS NULL"))

    # Now make the column NOT NULL
    op.alter_column('organizations', 'is_default', nullable=False)

    # Add content_full field to documents table (from deleted migration 890b361d4089)
    op.add_column('documents', sa.Column('content_full', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove fields added in upgrade (reverse order)
    op.drop_column('documents', 'content_full')
    op.drop_column('organizations', 'is_default')

    # ### end Alembic commands ###
