#!/bin/sh
set -e

echo "🔧 PrivexBot Frontend - Configuring runtime environment..."

# Default values for environment variables
API_BASE_URL=${API_BASE_URL:-https://api.privexbot.com/api/v1}
WIDGET_CDN_URL=${WIDGET_CDN_URL:-https://widget.privexbot.com}
ENVIRONMENT=${ENVIRONMENT:-production}

echo "📋 Runtime Configuration:"
echo "  API_BASE_URL: $API_BASE_URL"
echo "  WIDGET_CDN_URL: $WIDGET_CDN_URL"
echo "  ENVIRONMENT: $ENVIRONMENT"

# Generate runtime configuration file
cat > /usr/share/nginx/html/config.js <<EOF
// Runtime Configuration (Generated at container startup)
// This file is dynamically generated by docker-entrypoint.sh

window.ENV_CONFIG = {
  API_BASE_URL: '${API_BASE_URL}',
  WIDGET_CDN_URL: '${WIDGET_CDN_URL}',
  ENVIRONMENT: '${ENVIRONMENT}'
};

console.log('🔧 Runtime config loaded:', window.ENV_CONFIG);
EOF

echo "✅ Runtime configuration generated successfully"
echo "🚀 Starting Nginx server..."

# Execute the original Nginx command
exec "$@"